actors/urls.py
from django.urls import path
from . import views

app_name="actors"

urlpatterns = [
    path('',views.search, name="search"),
    path('id_<int:actor_id>/',views.detail, name="detail"),
    path('id_<int:actor_id>/like', views.like_actor, name="like"),
    path('recommand/movie/',views.recommand_movie, name="recommand_movie"),
    path('recommand/actor/',views.recommand_actor, name="recommand_actor"),
    path('viewed/<int:movie_id>/',views.viewed_movie, name="viewed_movie"),
    path('id_<int:actor_id>/rating/', views.create_rating, name="create_rating"),
    path('id_<int:actor_id>/rating/<int:rating_id>/', views.update_rating, name="update_rating"),
    path('id_<int:actor_id>/rating/<int:rating_id>/delete/', views.delete_rating, name="delete_rating"),
    path('create/',views.create_actor, name="create_actor"),
    path('id_<int:actor_id>/update/',views.edit_actor, name="edit_actor"),
]

ebaeu/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from rest_framework_swagger.views import get_swagger_view
from accounts import views as accounts_views
from actors import views as actors_views

schema_view = get_swagger_view(title='Movie API')

urlpatterns = [
    url('api/v1/docs', schema_view),
    path('', actors_views.index, name='main'),
    path('admin/', admin.site.urls),
    path('actors/', include('actors.urls')),
    path('accounts/', include('accounts.urls')),
    path('@<str:username>/', accounts_views.profile, name='profile'),
]

actors/models.py
from django.db import models
from django.conf import settings
from django.db.models import Avg
from django.core.validators import MaxValueValidator, MinValueValidator
# Create your models here.


class Actor (models.Model):
    name = models.CharField(max_length=255)
    image = models.URLField(max_length=255)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_actors', blank=True)

    @property
    def get_point(self):
        avg_score = self.movies.aggregate(Avg('score'))['score__avg'] if self.movies.aggregate(Avg('score'))['score__avg'] else 0
        avg_aud = self.movies.aggregate(Avg('normalized_audience'))['normalized_audience__avg'] if self.movies.aggregate(Avg('normalized_audience'))['normalized_audience__avg'] else 0
        avg_sales = self.movies.aggregate(Avg('normalized_sales'))['normalized_sales__avg'] if self.movies.aggregate(Avg('normalized_sales'))['normalized_sales__avg'] else 0
        return sum([avg_score*2, avg_aud*1, avg_sales*1])/4
        
    def __str__(self):
        return self.name


class Genre(models.Model):
    type = models.CharField(max_length=255)
    
    def __str__(self):
        return self.type


class Movie(models.Model):
    code=models.IntegerField()
    title = models.CharField(max_length=255)
    score = models.FloatField(default=0)
    sales = models.BigIntegerField()
    normalized_sales = models.FloatField(default=0)
    audience = models.BigIntegerField()
    normalized_audience = models.FloatField(default=0)
    open_date=models.DateField()
    poster_URL = models.URLField(max_length=255)
    summary = models.TextField()
    actors = models.ManyToManyField(Actor, related_name="movies")
    genres = models.ManyToManyField(Genre, related_name="movies")
    viewed_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='viewed_movies', blank=True)
    
    def __str__(self):
        return self.title


class Rating(models.Model):
    comment = models.CharField(max_length=255)
    score = models.IntegerField(validators=[
            MaxValueValidator(10),
            MinValueValidator(1)
        ])
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    actor = models.ForeignKey(
        Actor, on_delete=models.CASCADE, related_name="ratings")
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="ratings")
    
    def __str__(self):
        return f'{self.user.username}: {self.score}'

actors/forms.py
from django import forms
from .models import Rating, Actor

class RatingForm(forms.ModelForm):
    score = forms.IntegerField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control"
            })    
        )
    comment = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control"
            })
        )
    class Meta:
        model = Rating
        fields = ['score', 'comment']
        
class ActorForm(forms.ModelForm):
    class Meta:
        model = Actor
        fields = ['name', 'image']

actors/views.py
from django.shortcuts import render, get_object_or_404,redirect
from rest_framework.response import Response
from rest_framework.decorators import api_view
from rest_framework import status
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.db.models import Avg, Count, Case, When, F
from .models import Actor, Movie, Genre, Rating
from .forms import RatingForm, ActorForm
# from .serializers import MovieSerializer, ActorSerializer, GenreSerializer, RatingSerializer
from django.http import HttpResponseRedirect
from django.views.decorators.http import require_POST
from django.contrib.auth import get_user_model


def index(request):
  sort = request.GET.get('sort')
  if not sort:
    sort = 2017
  actors = Actor.objects.annotate(
    movie_count=Count(
      Case(
        When(movies__open_date__year__in = range(int(sort), 2020), then=F('movies'))
      )
    )
  ).filter(movie_count__gte=3)
  actors = sorted(actors, key=lambda x:x.get_point, reverse=True)[:10]
  return render(request,'actors/index.html', {'actors': actors, 'years': range(2010, 2020)})


def search(request):
  query = request.GET.get('q')
  if query:
    actors = Actor.objects.filter(name__icontains = query)
    return render(request,'actors/index.html', {'actors': actors})
  else:
    return redirect('main')


def detail(request, actor_id):
  actor = get_object_or_404(Actor,pk=actor_id)
  return render(request,'actors/detail.html', {'actor':actor, 'form': RatingForm(), 'update': False})


@login_required  
def like_actor(request, actor_id):
  actor = get_object_or_404(Actor,pk=actor_id)
  if request.user in actor.like_users.all():
    actor.like_users.remove(request.user)
  else:
    actor.like_users.add(request.user)
  return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required  
def viewed_movie(request, movie_id):
  movie = get_object_or_404(Movie,pk=movie_id)
  if request.user in movie.viewed_users.all():
    movie.viewed_users.remove(request.user)
  else:
    movie.viewed_users.add(request.user)
  return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required  
def recommand_movie(request):
  user=request.user
  like_actors=user.like_actors.all()
  return render(request,'actors/recommandMovie.html',{'like_actors':like_actors})


@login_required
def recommand_actor(request):
  viewed_movies=request.user.viewed_movies.all()
  return render(request,'actors/recommandActor.html',{'viewed_movies':viewed_movies})
  
  
@login_required
@require_POST
def create_rating(request, actor_id):
  form = RatingForm(request.POST)
  if form.is_valid():
    rating = form.save(commit=False)
    rating.user = request.user
    rating.actor_id = actor_id
    rating.save()
  return redirect('actors:detail', actor_id)
  
  
@login_required
def update_rating(request, actor_id, rating_id):
  rating = get_object_or_404(Rating, id=rating_id)
  if request.method == 'POST':
    if rating.user == request.user:
      form = RatingForm(request.POST, instance=rating)
      if form.is_valid():
        form.save()
    return redirect('actors:detail', actor_id)
  else:
    form = RatingForm(instance=rating)
    actor = get_object_or_404(Actor,pk=actor_id)
    return render(request,'actors/detail.html',{'actor':actor, 'form': form, 'update': True, 'rating_id':rating_id})


@login_required
@require_POST
def delete_rating(request, actor_id, rating_id):
  rating = get_object_or_404(Rating, id=rating_id)
  if rating.user == request.user:
    rating.delete()
  return redirect('actors:detail', actor_id)


@staff_member_required
def create_actor(request):
  if request.method == 'POST':
    form = ActorForm(require_POST)
    if form.is_valid():
      form.save()
    return redirect('main')
  else:
    form = ActorForm()
    return render(request, 'actors/form.html', {'form': form, 'name': '등록'})


@staff_member_required
def edit_actor(request, actor_id):
  actor = get_object_or_404(Actor, id=actor_id)
  if request.method == 'POST':
    form = ActorForm(request.POST, instance=actor)
    if form.is_valid():
      form.save()
    return redirect('actors:detail', actor_id)
  else:
    form = ActorForm(instance=actor)
    return render(request, 'actors/form.html', {'form': form, 'name': '수정'})

actors/templates/actors/detail.html
{% extends 'base.html' %}
{% load mathfilters %}
{% load humanize %}
{% load bootstrap4 %}

{% block title %}
배우상세정보 - {{actor.name}}
{% endblock title %}

{% block body %}
<button type="button" onclick="goBack()" class="btn btn-dark btn-lg my-3">뒤로가기</button>
<!-- 배우 정보 -->
<div class="card">
  <div class="row col-8 offset-2 my-2">
    <div class="col-sm-12 col-md-3 d-flex align-items-center justify-content-center">
      <a href="{% url 'actors:detail' actor.id %}">
        <img src={{actor.image}} class="card-img" alt="profile" style="height:180px; width:auto">
      </a>
    </div>
    <div class="col-sm-12 col-md-9 d-flex align-items-center justify-content-center">
      <div class="card-body">
        <div>
          <h3 class="card-title">{{actor.name}}  
            <a href="{% url 'actors:like' actor.id %}" style="color: #db7093">
              {% if user in actor.like_users.all %}
                <i class="fas fa-heart"></i>
              {% else %}
                <i class="far fa-heart"></i>
              {% endif %}
            </a>
          </h3>
          <h5><button class="btn btn-link px-1" data-toggle="modal" data-target="#likeModal">{{ actor.like_users.count }}</button>명이 좋아합니다.</h5>
        </div>
          <div class="stars-container" style="word-wrap:normal;font-size: 30px; width: 5em; height: 45px;">
            <span class="stars-before">★★★★★</span>
            <span class="stars-after" style="width:{{ actor.get_point|mul:10 }}%">★★★★★</span>
          </div>
         <span style="position: absolute;font-size:20px;margin-top:0.6rem">신뢰도 {{ actor.get_point|mul:10|floatformat }}%</span>
      </div>
    </div>
    <!-- 배우 정보 끝 -->
  </div>
  {% include 'like_modal.html' %}
  <hr>
  <!--리뷰 자리-->
  <div class="row mx-2">
    <div class="col-sm-12 col-md-8" style="height: 300px; overflow-y: scroll;">
      <h5 class="mb-2">리뷰</h5>
      {% if actor.ratings.all %}
        <ul class="list-group overflow-auto">
          {% for rating in actor.ratings.all %}
            <li class="list-group-item">
              <form method="post" action="{% url 'actors:delete_rating' actor.id rating.id %}">
                {% csrf_token %}
                <p class="">
                  <a class="mr-3" href="mailto:">{{ rating.user.username }}</a>
                  {% if user == rating.user %}
                    <a class="mx-1" href="{% url 'actors:update_rating' actor.id rating.id %}"><i class="far fa-edit fa-lg"></i></a>
                    <button class="btn btn-link mx-1 b-0 p-0" type="submit"><i class="fas fa-eraser fa-lg"></i></button>
                  {% endif %}
                </p>
                <div class="d-flex">
                  <span class="badge badge-info badge-pill mr-3">{{ rating.score }}점</span>
                  <span class="mr-auto">{{ rating.comment }}</span>
                </div>
              </form>
            </li>
          {% endfor %}
        </ul>
      {% endif %}
    </div>
    <div class="col-sm-12 col-md-4">
      <h5 class="mb-3">리뷰 작성하기</h5>
      {% if update %}
      <form method="post" action="{% url 'actors:update_rating' actor.id rating_id %}">
          {% csrf_token %}
          <!--{% bootstrap_form form %}-->
          {% bootstrap_form form %}
          <button class="btn btn-primary" type="submit">작성</button>
      </form>
      {% else %}
      <form method="post" action="{% url 'actors:create_rating' actor.id %}">
          {% csrf_token %}
          <!--{% bootstrap_form form %}-->
          {% bootstrap_form form %}
          <button class="btn btn-primary" type="submit">작성</button>
      </form>
      {% endif %}
    </div>
  </div>
  <!--리뷰 끝-->
  <hr>
  <div class="row no-gutters m-1">
    <div class="container mt-1" style="padding-left: 20px; padding-right: 20px">
      <div class="row">
        {% for movie in actor.movies.all %}
        <!-- 영화 카드 시작 -->
        <div class="col-sm-12 col-md-4">
          <div class="card px-0 my-1">
            <img src={{movie.poster_URL}} class="card-img-top" alt="poster" data-target="#movie-modal{{movie.id}}"
              data-toggle="modal">
            <div class="card-body" style="padding: 1rem;">
              <h5 class="card-title mb-1">{{movie.title}}</h5>
              <span class="badge badge-primary" style="font-size: 13px">{{movie.score}}</span>
              <p class="card-text"><small class="text-muted">{{movie.open_date}}</small></p>
              <p class="card-text"><small class="text-muted">
                  {% for genre in movie.genres.all %}
                  {{genre.type}}
                  {% endfor %}
                </small></p>
              <a href="{% url 'actors:viewed_movie' movie.id %}">
                {% if user in movie.viewed_users.all %}
                <button class="btn btn-danger" style="font-size: 12px">봤어요</button>
                <!--아니면 -->
                {% else %}
                <button class="btn btn-primary" style="font-size: 12px">안봤어요</button>
                {% endif %}
              </a>
            </div>
          </div>
        </div>
        <!-- 영화 카드 끝 -->
        {% include 'movie_modal.html' %}
        {% endfor %}
      </div>
    </div>
  </div>
</div>
<script>
  function goBack() {
    window.history.back();
  }
</script>
{% endblock%}

actors/templates/actors/form.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block title %}
  영화 {{ name }}
{% endblock %}

{% block body %}
  <div class="col-6 offset-3">
    <h1 class="my-4">영화 {{ name }}</h1>
    <form method='POST'>
      {% csrf_token %}
      {% bootstrap_form form %}
      {% buttons %}
        <button type=submit class='btn btn-primary'>{{ name }}</button>
      {% endbuttons %}
    </form>
  </div>
{% endblock %}

actors/templates/actors/index.html
{% extends 'base.html' %}
{% load mathfilters %}

{% block title %}
main
{% endblock title %}

{% block body %}
{% if years %}
  <div class="btn-group my-2" role="group" aria-label="Button group with nested dropdown">
    <div class="btn-group" role="group" aria-label="Basic example">
      <button id="btnGroupDrop1" type="button" class="btn btn-dark dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        연도별 순위 보기
      </button>
      <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
        {% for year in years %}
        <a class="dropdown-item" href="{{ request.path }}?sort={{ year }}">{{ year }}</a>
        {% endfor %}
      </div>
    </div>
  </div>
{% endif %}

<!-- 배우 순위 시작-->
{% for actor in actors %}
<div class="card mt-2 mb-1">
  <a class="noLink" href="{% url 'actors:detail' actor.id %}">
    <div class="row no-gutters ">
      <div class="col-sm-12 col-md-4 d-flex justify-content-center align-items-center" style="height:150px">
        <div class="col-4 pr-2">
          <h5 class="text-center">
            {{ forloop.counter }}
            <br>
          </h5>
        </div>
        <div class="col-8">
          <img src="{{ actor.image }}" class="card-img" alt="profile" style="width: auto; height: 120px;">
        </div>
      </div>
      <div class="col-sm-12 col-md-8">
        <div class="card-body">
          <h5 class="card-title mt-3">{{ actor.name }}</h5>
          <p class="card-text">
            <div class="stars-container" style="word-wrap:normal; font-size: 30px; width: 5em; height: 45px;">
              <span class="stars-before">★★★★★</span>
              <span class="stars-after" style="width:{{ actor.get_point|mul:10 }}%">★★★★★</span>
            </div>
            <span style="position: absolute;font-size:20px;margin-top:0.6rem">신뢰도 {{ actor.get_point|mul:10|floatformat }}%</span>
          </p>
        </div>
      </div>
    </div>
  </a>
</div>
{% endfor %}
<!-- 배우 순위 카드 끝 -->
{% endblock %}

actors/templates/actors/recommand.html
{% extends 'bns.html' %}
{% load mathfilters %}
{% load humanize %}

{% block title %}
영화 추천
{% endblock title %}

{% block body2 %}

<h2 class="mr-3 my-3">- 영화 추천</h2>
{% for actor in like_actors %}

<!-- 배우 정보 -->
<div class="card mb-2">
  <div class="row no-gutters mb-1">
    <div class="col-4 d-flex justify-content-center align-items-center" style="height:150px">
      <div class="col-4 pr-2"></div>
      <div class="col-8">
        <img src={{actor.image}} class="card-img" alt="profile" style="width: auto; height: 125px;">
      </div>
    </div>
    <div class="col-8">
      <div class="card-body" style="padding: 1rem; margin-left: 16px;">
        <div class="mt-3">
          <h5 class="card-title d-inline">{{actor.name}}</h5>
          <a href="{% url 'actors:like' actor.id %}" style="color: red">
            {% if user in actor.like_users.all %}
            <i class="fas fa-heart"></i>
            {% else %}
            <i class="far fa-heart"></i>
            {% endif %}
          </a>
        </div>
        <p class="card-text">
          <div class="stars-container" style="word-wrap:normal;font-size: 30px; width: 5em; height: 45px;">
            <span class="stars-before">★★★★★</span>
            <span class="stars-after" style="width:{{ actor.get_point|mul:10 }}%">★★★★★</span>
          </div>
          <span class="ml-3" style="position: absolute;font-size:20px;margin-top:0.6rem">{{ actor.get_point|floatformat }}점</span>
        </p>
      </div>
    </div>
    <!-- 배우 정보 끝 -->
    <hr style="width:70px;border: 1px solid orange;">
    <div class="container mt-1" style="padding-left: 20px; padding-right: 20px">
      <div class="row">

        {% for movie in actor.movies.all %}
        {% if movie not in user.viewed_movies.all %}

        
        <!-- 영화 카드 시작 -->
        <div class="col-4 px-1" style="width: 18rem;">
          <div class="card px-0 my-1">
            <img src={{movie.poster_URL}} class="card-img-top" alt="poster" data-target="#movie-modal{{movie.id}}"
              data-toggle="modal">
            <div class="card-body" style="padding: 1rem;">
              <h5 class="card-title mb-1">{{movie.title}}</h5>
              <span class="badge badge-primary" style="font-size: 13px">{{movie.score}}</span>
              <p class="card-text"><small class="text-muted">{{movie.open_date}}</small></p>
              <p class="card-text"><small class="text-muted">
                  {% for genre in movie.genres.all %}
                  {{genre.type}}
                  {% endfor %}
                </small></p>
              <a href="{% url 'actors:viewed_in_recommand' movie.id %}">
                {% if user in movie.viewed_users.all %}
                <button class="btn btn-danger" style="font-size: 12px">봤어요</button>
                <!--아니면 -->
                {% else %}
                <button class="btn btn-primary" style="font-size: 12px">안봤어요</button>
                {% endif %}
              </a>
            </div>
          </div>
        </div>
        <!-- 영화 카드 끝 -->
        <!-- 영화 모달 시작-->
        <div class="modal fade" id="movie-modal{{movie.id}}" tabindex="-1" role="dialog"
          aria-labelledby="MovieModalLabel{{movie.id}}" aria-hidden="true">
          <div class="modal-dialog" role="document" style="width: 450px;">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="MovieModalLabel{{movie.id}}">{{movie.title}}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <img src={{movie.poster_URL}} class="card-img-top" alt="poster">
              <div class="modal-body">
                <p><i class="fas fa-star-half-alt"></i> {{movie.score}} / 10</p>
                <p><i class="fas fa-users"></i> {{movie.audience|intcomma}} 명</p>
                <p><i class="fas fa-won-sign"></i> {{movie.sales|intcomma}} 원</p>
                <p>
                  <hr>
                </p>
                <p><i class="fas fa-theater-masks"></i>
                  {% for actor in movie.actors.all %}
                  <a href="{% url 'actors:detail' actor.id %}">{{actor.name}} </a>
                  {% endfor %}
                </p>
                <p>
                  <hr>
                </p>
                <p>{{movie.summary}}</p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>
        <!-- 영화 모달 끝 -->

        {% endif %}
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endfor %}

{% endblock body2 %}

actors/templates/actors/recommandActor.html
{% extends 'base.html' %}
{% load mathfilters %}
{% load humanize %}

{% block title %}
배우 추천
{% endblock title %}

{% block body %}
  {% for movie in viewed_movies %}
    <div class="card my-2">
      <div class="row no-gutters mb-1">
        <div class="col-3">
          <div class="m-3">
            <img src="{{ movie.poster_URL }}" class="card-img" alt="{{ movie.title }}" data-target="#movie-modal{{movie.id}}" data-toggle="modal">
            <h5 class="card-title mt-2 text-center">{{ movie.title }}</h5>
          </div>
        </div>
        <div class="col-9" style="height: 400px; overflow-y: scroll;">
          <div class="card-body" style="padding: 1rem; margin-left: 16px;">
            <div class="row mt-2">
              {% for actor in movie.actors.all %}
                {% if actor not in user.like_actors.all %}
                  <div class="col-4 col-md-3 col-lg-2">
                    <a href="{% url 'actors:detail' actor.id %}">
                      <img src="{{ actor.image }}" class="card-img" alt="{{ actor.name }}">
                    </a>
                    <p class="text-center mt-1">
                      {{ actor.name }}
                      <a href="{% url 'actors:like' actor.id %}" style="color: #c71585">
                      {% if user in actor.like_users.all %}
                        <i class="fas fa-heart"></i>
                      {% else %}
                        <i class="far fa-heart"></i>
                      {% endif %}
                    </a>
                    </p>
                  </div>
                {% endif %}
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
    {% include 'movie_modal.html' %}
  {% endfor %}

{% endblock %}

actors/templates/actors/recommandMovie.html
{% extends 'base.html' %}
{% load mathfilters %}
{% load humanize %}

{% block title %}
영화 추천
{% endblock title %}

{% block body %}
{% for actor in like_actors %}

  <!-- 배우 정보 -->
  <div class="card my-2">
    <div class="row col-6 offset-3 mt-2">
      <div class="col-3 d-flex align-items-center justify-content-center">
        <a href="{% url 'actors:detail' actor.id %}">
          <img src={{actor.image}} class="card-img" alt="profile" style="height:120px; width:auto">
        </a>
      </div>
      <div class="col-9">
        <div class="card-body">
          <div>
            <h4 class="card-title d-inline">{{actor.name}}</h4>
            <a href="{% url 'actors:like' actor.id %}" style="color: #db7093">
              {% if user in actor.like_users.all %}
              <i class="fas fa-heart fa-lg"></i>
              {% else %}
              <i class="far fa-heart fa-lg"></i>
              {% endif %}
            </a>
          </div>
            <div class="stars-container" style="word-wrap:normal;font-size: 30px; width: 5em; height: 45px;">
              <span class="stars-before">★★★★★</span>
              <span class="stars-after" style="width:{{ actor.get_point|mul:10 }}%">★★★★★</span>
            </div>
            <span style="position: absolute;font-size:20px;margin-top:0.6rem">신뢰도 {{ actor.get_point|mul:10|floatformat }}%</span>
            <div class="d-flex align-items-center justify-content-center">
              <a data-toggle="collapse" href="#collapseMovie{{ actor.id }}" role="button" aria-expanded="false" aria-controls="collapseMovie{{ actor.id }}">
                <i class="fas fa-chevron-down fa-2x" style="color: #d2b48c"></i>
              </a>
            </div>
        </div>
      </div>
    </div>
    <!-- 배우 정보 끝 -->
    <div class="collapse mt-1" id="collapseMovie{{ actor.id }}" style="padding-left: 20px; padding-right: 20px">
      <div class="row">
        {% for movie in actor.movies.all %}
          {% if movie not in user.viewed_movies.all %}
            <!-- 영화 카드 시작 -->
            <div class="col-3 px-1" style="width: 18rem;">
              <div class="card px-0 my-1">
                <img src={{movie.poster_URL}} class="card-img-top" alt="poster" data-target="#movie-modal{{movie.id}}"
                  data-toggle="modal">
                <div class="card-body" style="padding: 1rem;">
                  <h5 class="card-title mb-1">{{movie.title}}</h5>
                  <span class="badge badge-primary" style="font-size: 13px">{{movie.score}}</span>
                  <p class="card-text"><small class="text-muted">{{movie.open_date}}</small></p>
                  <p class="card-text"><small class="text-muted">
                      {% for genre in movie.genres.all %}
                      {{genre.type}}
                      {% endfor %}
                    </small></p>
                  <a href="{% url 'actors:viewed_movie' movie.id %}">
                    {% if user in movie.viewed_users.all %}
                      <button class="btn btn-danger" style="font-size: 12px">봤어요</button>
                    {% else %}
                      <button class="btn btn-primary" style="font-size: 12px">안봤어요</button>
                    {% endif %}
                  </a>
                </div>
              </div>
            </div>
            <!-- 영화 카드 끝 -->
            {% include 'movie_modal.html' %}
          {% endif %}
        {% endfor %}
      </div>
    </div>
  </div>
{% endfor %}

{% endblock %}